CREATE TABLE `admin_users`
(
    `id`         INT(10) UNSIGNED NOT NULL AUTO_INCREMENT,
    `nickname`   VARCHAR(50) CHARACTER SET utf8 NOT NULL DEFAULT '' COMMENT '昵称',
    `username`   VARCHAR(50) CHARACTER SET utf8 NOT NULL DEFAULT '' COMMENT '用户名',
    `password`   VARCHAR(255) CHARACTER SET utf8 NOT NULL DEFAULT '' COMMENT '密码',
    `status`     TINYINT(1) NOT NULL DEFAULT '0' COMMENT '状态(-1:删除,0:正常,1:暂停)',
    `role_id`    INT(10) UNSIGNED NOT NULL DEFAULT '0' COMMENT '角色ID',
    `created_at` TIMESTAMP                      NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '记录创建时间',
    `updated_at` TIMESTAMP                      NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '记录更新时间',
    PRIMARY KEY (`id`) USING BTREE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 ROW_FORMAT=DYNAMIC COMMENT='后台用户信息';
